#!/bin/bash

echo "Setting up ADB over Wi-Fi"
echo "========================="
echo ""
echo "Step 1: Connect your Android device via USB first"
echo "Step 2: Make sure USB debugging is enabled"
echo "Step 3: Run the following commands:"
echo ""
echo "# Enable TCP/IP mode on port 5555"
echo "adb tcpip 5555"
echo ""
echo "# Find your device IP address (on your phone: Settings > About > Status > IP Address)"
echo "# Or run: adb shell ip route | awk '{print \$9}' | head -1"
echo ""
echo "# Connect wirelessly (replace YOUR_DEVICE_IP with actual IP)"
echo "adb connect YOUR_DEVICE_IP:5555"
echo ""
echo "# Disconnect USB cable and verify wireless connection"
echo "adb devices"
echo ""
echo "# To disconnect wireless debugging"
echo "adb disconnect YOUR_DEVICE_IP:5555"

